# Generated by Django 4.0.5 on 2022-06-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatmatrix',
            name='total',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Total'),
        ),
    ]
