# Generated by Django 4.0.5 on 2022-06-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seatmatrix_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatmatrix',
            name='agl',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='AGL'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='cap',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='CAP'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='d',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='D'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='dk',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='DK'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='jk',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='JK'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='ncc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='NCC'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='ph',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='PH'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='pv',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='PV'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='sg',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='S-G'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='spo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='SPO'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='total_gen',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Total general reserved seats'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='total_hyd',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Total Hyd Kar Reserved Seats'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='total_spl',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Total Special Reserved Seats'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='xcp',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='XCP'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='xd',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='XD'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='total',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='All Total Reserved Seats'),
        ),
    ]
