# Generated by Django 4.0.5 on 2022-06-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seatmatrix_agl_seatmatrix_cap_seatmatrix_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoff',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cutoff',
            name='code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cutoff',
            name='college',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cutoff',
            name='course',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cutoff',
            name='round',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_1g',
            field=models.IntegerField(blank=True, null=True, verbose_name='1G'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_1h',
            field=models.IntegerField(blank=True, null=True, verbose_name='1H'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_1k',
            field=models.IntegerField(blank=True, null=True, verbose_name='1K'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_1kh',
            field=models.IntegerField(blank=True, null=True, verbose_name='1KH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_1r',
            field=models.IntegerField(blank=True, null=True, verbose_name='1R'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_1rh',
            field=models.IntegerField(blank=True, null=True, verbose_name='1RH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_2ag',
            field=models.IntegerField(blank=True, null=True, verbose_name='2AG'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_2ah',
            field=models.IntegerField(blank=True, null=True, verbose_name='2AH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_2ak',
            field=models.IntegerField(blank=True, null=True, verbose_name='2AK'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_2akh',
            field=models.IntegerField(blank=True, null=True, verbose_name='2AKH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_2ar',
            field=models.IntegerField(blank=True, null=True, verbose_name='2AR'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_2arh',
            field=models.IntegerField(blank=True, null=True, verbose_name='2ARH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_2bg',
            field=models.IntegerField(blank=True, null=True, verbose_name='2BG'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_2bh',
            field=models.IntegerField(blank=True, null=True, verbose_name='2BH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_2bk',
            field=models.IntegerField(blank=True, null=True, verbose_name='2BK'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_2bkh',
            field=models.IntegerField(blank=True, null=True, verbose_name='2BKH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_2br',
            field=models.IntegerField(blank=True, null=True, verbose_name='2BR'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_2brh',
            field=models.IntegerField(blank=True, null=True, verbose_name='2BRH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_3ag',
            field=models.IntegerField(blank=True, null=True, verbose_name='3AG'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_3ah',
            field=models.IntegerField(blank=True, null=True, verbose_name='3AH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_3ak',
            field=models.IntegerField(blank=True, null=True, verbose_name='3AK'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_3akh',
            field=models.IntegerField(blank=True, null=True, verbose_name='3AKH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_3ar',
            field=models.IntegerField(blank=True, null=True, verbose_name='3AR'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_3arh',
            field=models.IntegerField(blank=True, null=True, verbose_name='3ARH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_3bg',
            field=models.IntegerField(blank=True, null=True, verbose_name='3BG'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_3bh',
            field=models.IntegerField(blank=True, null=True, verbose_name='3BH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_3bk',
            field=models.IntegerField(blank=True, null=True, verbose_name='3BK'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_3bkh',
            field=models.IntegerField(blank=True, null=True, verbose_name='3BKH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_3br',
            field=models.IntegerField(blank=True, null=True, verbose_name='3BR'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='_3brh',
            field=models.IntegerField(blank=True, null=True, verbose_name='3BRH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='agl',
            field=models.IntegerField(blank=True, null=True, verbose_name='AGL'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='cap',
            field=models.IntegerField(blank=True, null=True, verbose_name='CAP'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='college_short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='College Short Name'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='course_code',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='course_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='d',
            field=models.IntegerField(blank=True, null=True, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='dk',
            field=models.IntegerField(blank=True, null=True, verbose_name='DK'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='gm',
            field=models.IntegerField(blank=True, null=True, verbose_name='GM'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='gmh',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='gmk',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMK'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='gmkh',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMKH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='gmp',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMP'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='gmr',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMR'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='gmrh',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMRH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='jk',
            field=models.IntegerField(blank=True, null=True, verbose_name='JK'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='ncc',
            field=models.IntegerField(blank=True, null=True, verbose_name='NCC'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='ph',
            field=models.IntegerField(blank=True, null=True, verbose_name='PH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='pv',
            field=models.IntegerField(blank=True, null=True, verbose_name='PV'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='scg',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCG'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='sch',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='sck',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCK'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='sckh',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCKH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='scr',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCR'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='scrh',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCRH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='sg',
            field=models.IntegerField(blank=True, null=True, verbose_name='S-G'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='snq',
            field=models.IntegerField(blank=True, null=True, verbose_name='SNQ'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='spo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SPO'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='stg',
            field=models.IntegerField(blank=True, null=True, verbose_name='STG'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='sth',
            field=models.IntegerField(blank=True, null=True, verbose_name='STH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='stk',
            field=models.IntegerField(blank=True, null=True, verbose_name='STK'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='stkh',
            field=models.IntegerField(blank=True, null=True, verbose_name='STKH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='str',
            field=models.IntegerField(blank=True, null=True, verbose_name='STR'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='strh',
            field=models.IntegerField(blank=True, null=True, verbose_name='STRH'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='All Total Reserved Seats'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='total_gen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total general reserved seats'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='total_hyd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Hyd Kar Reserved Seats'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='total_spl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Special Reserved Seats'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='xcp',
            field=models.IntegerField(blank=True, null=True, verbose_name='XCP'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='xd',
            field=models.IntegerField(blank=True, null=True, verbose_name='XD'),
        ),
    ]
