# Generated by Django 4.0.5 on 2022-06-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cutoff_category_alter_cutoff_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatmatrix',
            name='course_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Code'),
        ),
    ]
